import { StyleSheet } from 'react-native';

export const fonts = {
  roboto400: 'Roboto-Regular',
  roboto500: 'Roboto-Medium',
  roboto700: 'Roboto-Bold',
};

export const styles = StyleSheet.create({
  // RegistrationAndLoginScreen
  imgBg: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'flex-end',
  },
  form: {
    position: 'relative',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingHorizontal: 16,
  },
  title: {
    color: '#212121',
    textAlign: 'center',
    fontFamily: fonts.roboto700,
    fontSize: 30,
    marginTop: 92,
    marginBottom: 32,
  },
  boxAvatar: {
    position: 'absolute',
    width: 120,
    height: 120,
    top: -60,
    right: '50%',
    borderRadius: 16,
    backgroundColor: '#F6F6F6',
  },
  buttonAddAvatar: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 81,
    left: 107,
    width: 25,
    height: 25,
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 50,
    backgroundColor: '#ffffff',
  },
  input: {
    height: 50,
    padding: 10,
    borderWidth: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    color: '#212121',
    fontFamily: fonts.roboto400,
    fontSize: 16,
    lineHeight: 18.75,
  },
  wrapperInput: { position: 'relative' },
  buttonShowPassword: {
    position: 'absolute',
    top: 15,
    right: 16,
    fontSize: 16,
    lineHeight: 18.75,
    color: '#1B4371',
  },
  link: {
    color: '#1B4371',
    fontFamily: fonts.roboto400,
    fontSize: 16,
    lineHeight: 18.75,
    textAlign: 'center',
  },
  // HomeScreen
  tabMenu: {
    height: 83,
    paddingTop: 9,
    boxShadow: '0px -0.5px 0px rgba(0, 0, 0, 0.3)',
    paddingLeft: 45,
  },
  // CreatePostsScreen
  imageBox: {
    width: '100%',
    height: 240,
    backgroundColor: '#F6F6F6',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    marginBottom: 8,
  },
  textStyle: {
    fontFamily: fonts.roboto400,
    fontSize: 16,
    lineHeight: 18.75,
    color: '#BDBDBD',
  },
  iconBox: {
    width: 60,
    height: 60,
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    position: 'absolute',
    left: '40%',
    top: '38%',
    justifyContent: 'center',
  },
  cameraIcon: {
    alignSelf: 'center',
  },
  inputPost: {
    height: 50,
    borderBottomWidth: 1,
    color: '#212121',
    fontFamily: fonts.roboto400,
    fontSize: 16,
    lineHeight: 18.75,
  },
});
